### ISSUE TITLE
Allow modules to be disabled

### ISSUE THREAD

**Issue by OscarOrSomething** [FoundationDriven/FoundationAPI#2]
Modules should be able to be disabled in case initialization fails (e.g. Invalid Config)

**Comment by sam4215** [comment]
I can do that.

**Comment by OscarOrSomething** [comment]
Nah, I'll do it soon once my laptop is sorted out.

**Comment by OscarOrSomething** [comment]
Implementing it on Foundation, See [#51](https://github.com/FoundationDriven/Foundation/issues/51)
